.. _compwa-expert-system:

The ComPWA Expert System
------------------------

The ComPWA expert system is a pure python package which can generate decay
intensities of arbitrary decays in the helicity or canonical formalism.

A typical analysis user only has to work with the user interface of the expert
system :mod:`pycompwa.expertsystem.ui`.

Most important is the StateTransitionManager

More info coming soon.
