"""Import data files generated by other PWA frameworks.

This is a collection of submodules that allow one to import collections of
4-momentum tuples of other PWA frameworks into a :class:`pandas.DataFrame` that
has the the format specified by :class:`~.PwaAccessor`. You can then use the
methods in :mod:`~.data.convert` to import the data into the ComPWA back-end.
"""

__all__ = [
    "pawian",
]


from . import pawian
